name: Check basic runs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-basic-runs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.5' # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 

    - name: Meva_BayDS_NoPrior
      run: python main.py --estimator None --dataset Meva --calibrator BayesianDawidSkene --compare_models gpt___s2s --calibrator_sample_size 20 --calibrator_sample_cores 2

    - name: Panda_OCDS_InDistPrior
      run: python main.py --estimator OneCoinBetaBernoulli --dataset PandaLM --calibrator OneCoinDawidSkene --q_prior_data_ratio 0.2 --compare_models bloom-7b___opt-7b

    - name: Hanna_DS_OODPrior
      run: python main.py --estimator BetaBernoulli --dataset Hanna --calibrator DawidSkene --compare_models BertGeneration___GPT --q_prior_ood

    - name: Panda_bwrs_InDistCV
      run: python main.py --estimator BetaBernoulli --dataset PandaLM --calibrator None --q_prior_cv_folds 2 --compare_models bloom-7b___opt-7b --plot_dir /dev/null

